require 'simplecov'
SimpleCov.start 'test_frameworks'

require 'rantly/property'
require 'rspec'
require 'zipr/either'
require 'zipr/enumerable-extensions'
require 'zipr/rantly-extensions'
require 'zipr/test-trees'
require 'zipr/trampoline'
require 'zipr/zipper'
